apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-api
  namespace: restaurant-api
  labels:
    app: restaurant-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-api
  template:
    metadata:
      labels:
        app: restaurant-api
    spec:
      containers:
      - name: restaurant-api
        image: your-dockerhub-username/restaurant-api:latest # Replace with your image
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: MONGO_URI
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: DB_NAME